### ISSUE TITLE
integration.sh e2e tests failing

### ISSUE THREAD

**Issue by GregBlow** [lsst/qserv-operator#58]
running e2e integration.sh tests fails. Final traceback:

```
Traceback (most recent call last):
  File "/ingest/bin/replctl", line 163, in <module>
    ingester.ingest(args.chunk_queue_fraction)
  File "/ingest/python/qserv/ingest.py", line 149, in ingest
    has_non_ingested_contributions = self._ingest_transaction()
  File "/ingest/python/qserv/ingest.py", line 251, in _ingest_transaction
    raise (e)
  File "/ingest/python/qserv/ingest.py", line 246, in _ingest_transaction
    ingest_success = self._ingest_all_contributions(transaction_id, contributions)
  File "/ingest/python/qserv/ingest.py", line 305, in _ingest_all_contributions
    c.finished = c.monitor()
  File "/ingest/python/qserv/contribution.py", line 227, in monitor
    raise IngestError(f"{msg} {noretry_errmsg}")
qserv.exception.IngestError: Contribution Contribution({'ext': 'txt', 'chunk_id': 57866, 'table': 'position', 'is_overlap': 0, 'charset_name': '', 'load_balanced_url': LoadBalancedURL({'direct_url': 'http://dataserver/datasets/DC2/step1_1/position/chunk_57866.txt', 'counter': <qserv.loadbalancerurl.LoadBalancerAlgorithm object at 0x7f960e951660>, 'url_path': '/datasets/DC2/step1_1/position/chunk_57866.txt', 'loadBalancerAlgorithm': <qserv.loadbalancerurl.LoadBalancerAlgorithm object at 0x7f960e951660>}), 'request_id': 25, 'worker_url': 'http://qserv-worker-0.qserv-worker.default.svc.cluster.local:25004', 'finished': False}) is in status ContributionState.LOAD_FAILED with error: Connection[131]::execute(_inTransaction=1)  mysql_real_query failed, query: 'LOAD DATA INFILE '/qserv/data/ingest/dc2_run2_1i_dr1b-position-57866-9-cc68-8f68-989e-bf59.csv' INTO TABLE `dc2_run2_1i_dr1b`.`position_57866` CHARACTER SET 'latin1' FIELDS TERMINATED BY ',' ESCAPED BY '\\' LINES TERMINATED BY '\n'', error: Incorrect integer value: 'version https://git-lfs.github.com/spec/v1' for column `dc2_run2_1i_dr1b`.`position_57866`.`objectId` at row 1, errno: 1366, system error: 11, http error: 0 and is not retriable
```

**Comment by GregBlow** [comment]
[integration_test_output.txt](https://github.com/lsst/qserv-operator/files/11051154/integration_test_output.txt)

**Comment by iagaponenko** [comment]
It looks like problems started much earlier. If you look at line 270 then you will see an attempt to ingest the first chunk of data into the test catalog:
```
2023-03-23 12:46:43,522 - qserv.contribution - DEBUG - start_async(): url: http://qserv-worker-0.qserv-worker.default.svc.cluster.local:25004/ingest/file-async
2023-03-23 12:46:43,522 - qserv.contribution - DEBUG - start_async(): payload: {'transaction_id': 14, 'table': 'position', 'chunk': 57866, 'overlap': 0, 'url': 'http://dataserver/datasets/DC2/step1_1/position/chunk_57866.txt', 'charset_name': '', 'fields_terminated_by': ','}
```
I _suspect_ this operation might fail. The corresponding Replication/Ingest system's worker (`qserv-worker-0`) sent back a response that could't be parsed by the Python code, which resulted in the following Python error:
```
raceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "/ingest/bin/replctl", line 163, in <module>
    ingester.ingest(args.chunk_queue_fraction)
  File "/ingest/python/qserv/ingest.py", line 149, in ingest
    has_non_ingested_contributions = self._ingest_transaction()
  File "/ingest/python/qserv/ingest.py", line 246, in _ingest_transaction
    ingest_success = self._ingest_all_contributions(transaction_id, contributions)
  File "/ingest/python/qserv/ingest.py", line 301, in _ingest_all_contributions
    c.start_async(transaction_id)
  File "/ingest/python/qserv/contribution.py", line 153, in start_async
```
Here is what I suggest to firther investigate the issue:
* check the log file of the worker by `kubectl logs qserv-worker-0 -c repl-wrk` and post the output here, please
* contact @fjammes (the developer of the integration test) to see what might be wrong with the Python code

**Comment by GregBlow** [comment]
[qserv-worker-0-repl-wrk.log](https://github.com/lsst/qserv-operator/files/11087990/qserv-worker-0-repl-wrk.log)

integration tests start at 2023-03-28T09:48:54 in this log file, it looks like. Thank you. 

Looking through the logs myself, we have:

```
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  DatabaseServicesMySQL::updateTransactionContrib id=80 ** DONE **
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  DatabaseServicesMySQL::ingestParam database=dc2_run2_1i_dr1b category=worker-http-file-reader param=SSL_VERIFYHOST
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  Connection[13]::executeInOwnTransaction(_inTransaction=0,maxRetriesOnDeadLock=0)  running user script, numRetriesOnDeadLock: 0
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  Connection[13]::execute(_inTransaction=0,effectiveMaxReconnects=1,effectiveTimeoutSec=3600)  running user script, numReconnects: 0
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  Connection[13]::begin(_inTransaction=0)  
2023-03-28T09:48:55.025Z  LWP 246   DEBUG  Connection[13]::execute(_inTransaction=0)  BEGIN
2023-03-28T09:48:55.026Z  LWP 246   DEBUG  DatabaseServicesMySQL::_ingestParamsImpl predicate=`database`='dc2_run2_1i_dr1b' AND `category`='worker-http-file-reader' AND `param`='SSL_VERIFYHOST' 
2023-03-28T09:48:55.026Z  LWP 246   DEBUG  Connection[13]::execute(_inTransaction=1)  SELECT * FROM `database_ingest` WHERE `database`='dc2_run2_1i_dr1b' AND `category`='worker-http-file-reader' AND `param`='SSL_VERIFYHOST'
2023-03-28T09:48:55.028Z  LWP 246   DEBUG  Connection[13]::rollback(_inTransaction=1)  
2023-03-28T09:48:55.028Z  LWP 246   DEBUG  Connection[13]::execute(_inTransaction=1)  ROLLBACK
2023-03-28T09:48:55.029Z  LWP 246   ERROR  DatabaseServicesMySQL::ingestParam database=dc2_run2_1i_dr1b category=worker-http-file-reader param=SSL_VERIFYHOSTfailed, exception: DatabaseServicesNotFound: DatabaseServicesMySQL::_ingestParamImpl predicate=`database`='dc2_run2_1i_dr1b' AND `category`='worker-http-file-reader' AND `param`='SSL_VERIFYHOST' no such parameter
2023-03-28T09:48:55.029Z  LWP 246   DEBUG  DatabaseServicesMySQL::ingestParam database=dc2_run2_1i_dr1b category=worker-http-file-reader param=SSL_VERIFYPEER
```
This isn't the first COMMIT action, and it looks like previous such complete without error.

Error message text suggests it might have something to do with SSL verification?

**Comment by GregBlow** [comment]
[qserv-worker-0-repl-wrk.log](https://github.com/lsst/qserv-operator/files/11102001/qserv-worker-0-repl-wrk.log)

Updated worker log after adjusting MySQL network permissions on jumphost.

**Comment by fjammes** [comment]
Hi @GregBlow , it seems it is a `git-lfs` error:
```
Connection[131]::execute(_inTransaction=1)  mysql_real_query failed, query: 'LOAD DATA INFILE '/qserv/data/ingest/dc2_run2_1i_dr1b-position-57866-9-cc68-8f68-989e-bf59.csv' INTO TABLE `dc2_run2_1i_dr1b`.`position_57866` CHARACTER SET 'latin1' FIELDS TERMINATED BY ',' ESCAPED BY '\\' LINES TERMINATED BY '\n'', error: Incorrect integer value: 'version https://git-lfs.github.com/spec/v1' for column `dc2_run2_1i_dr1b`.`position_57866`.`objectId` at row 1, errno: 1366, system error: 11, http error: 0 and is not retriable
```
You need to install `git-lfs` before cloning `qserv-ingest` repository in order to get the correct integration test datasets.
You can check the clone is correct by running:
```
head itest/datasets/DC2/position.json 
{
    "version":12,
    "database": "dc2_run2_1i_dr1b",
    "table": "position",
    "auth_key": "",
    "is_partitioned": 1,
    "director_table": "",
    "director_key": "objectId",
    "latitude_key": "coord_dec",
    "longitude_key": "coord_ra",
```
in the `qserv-ingest` repository.

Could you please install `git-lfs` and re-clone `qserv-ingest` repository and let me know if it works? If it works, could you please send me the command to install `git-lfs` so that I update the qserv-ingest doc accordingly?

Thanks!

**Comment by GregBlow** [comment]
As of right now it certainly appears to be functioning better. The tests have been running for 15 minutes, which is significantly longer than in earlier versions. 
```
Name:                qserv-ingest-d4djv
Namespace:           default
ServiceAccount:      argo-workflow
Status:              Running
Conditions:
 PodRunning          True
Created:             Wed Apr 12 10:04:15 +0000 (16 minutes ago)
Started:             Wed Apr 12 10:04:20 +0000 (16 minutes ago)
Duration:            16 minutes 5 seconds
Progress:            2/3
ResourcesDuration:   6s*(1 cpu),6s*(100Mi memory)
Parameters:
  image:             qserv/ingest:2023.4.1-rc1
  verbose:           2
  superTransactions: 10
  backoffLimit:      5

STEP                   TEMPLATE      PODNAME                        DURATION  MESSAGE
 ● qserv-ingest-d4djv  main
 ├─✔ queue             ingest-step   qserv-ingest-d4djv-3228306683  6s
 ├─✔ register          ingest-step   qserv-ingest-d4djv-2597444989  6s
 └─● transactions      transactions  qserv-ingest-d4djv-3449966493  15m

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```
None of the associated pods have errored out.
```
default                 qserv-ingest-transactions-cq8wq-b7zqr                 1/1     Running            0
   14m   10.47.0.6     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-h489k                 1/1     Running            0
   14m   10.47.0.8     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-h4hfv                 1/1     Running            0
   14m   10.42.0.9     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-j6zxc                 1/1     Running            0
   14m   10.42.0.5     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-p4sqt                 1/1     Running            0
   14m   10.47.0.7     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-qs2ll                 1/1     Running            0
   14m   10.42.0.7     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-sf6xt                 1/1     Running            0
   14m   10.42.0.6     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-tnmcm                 1/1     Running            0
   14m   10.47.0.4     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-wqkh5                 1/1     Running            0
   14m   10.42.0.8     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-zr7vz                 1/1     Running            0
```
```
   14m   10.47.0.4     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-d4djv-3449966493                         1/1     Running            0
   14m   10.42.0.4     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-db-0                                     1/1     Running            0
```
I'd wait for completion to update, but as it's taking considerably longer than expected I thought I'd post an update as it ran.

**Comment by GregBlow** [comment]
tests are still running after two hours, but from looking at the logs it doesn't appear to be looping infinitely, just taking a fair old while. Has the specification/purpose of the integration tests changed please? They would previously take approximately 2 minutes. 
[qserv-worker-1-repl-wrk.log](https://github.com/lsst/qserv-operator/files/11211203/qserv-worker-1-repl-wrk.log)
[qserv-ingest.transactions-cq8wq-b7zqr.log](https://github.com/lsst/qserv-operator/files/11211204/qserv-ingest.transactions-cq8wq-b7zqr.log)
```
Name:                qserv-ingest-d4djv
Namespace:           default
ServiceAccount:      argo-workflow
Status:              Running
Conditions:
 PodRunning          True
Created:             Wed Apr 12 10:04:15 +0000 (2 hours ago)
Started:             Wed Apr 12 10:04:20 +0000 (2 hours ago)
Duration:            2 hours 15 minutes
Progress:            2/3
ResourcesDuration:   6s*(1 cpu),6s*(100Mi memory)
Parameters:
  image:             qserv/ingest:2023.4.1-rc1
  verbose:           2
  superTransactions: 10
  backoffLimit:      5

STEP                   TEMPLATE      PODNAME                        DURATION  MESSAGE
 ● qserv-ingest-d4djv  main
 ├─✔ queue             ingest-step   qserv-ingest-d4djv-3228306683  6s
 ├─✔ register          ingest-step   qserv-ingest-d4djv-2597444989  6s
 └─● transactions      transactions  qserv-ingest-d4djv-3449966493  2h

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```
```
default                 qserv-ingest-transactions-cq8wq-b7zqr                 1/1     Running            0             135m   10.47.0.6     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-h489k                 1/1     Running            0             135m   10.47.0.8     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-h4hfv                 1/1     Running            0             135m   10.42.0.9     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-j6zxc                 1/1     Running            0             135m   10.42.0.5     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-p4sqt                 1/1     Running            0             135m   10.47.0.7     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-qs2ll                 1/1     Running            0             135m   10.42.0.7     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-sf6xt                 1/1     Running            0             135m   10.42.0.6     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-tnmcm                 1/1     Running            0             135m   10.47.0.4     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-wqkh5                 1/1     Running            0             135m   10.42.0.8     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cq8wq-zr7vz                 1/1     Running            0             135m   10.47.0.5     sv-qserv-worker-4    <none>           <none>
```
```
default                 qserv-ingest-d4djv-2597444989                         0/2     Completed          0             135m   10.47.0.5     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-d4djv-3228306683                         0/2     Completed          0             135m   10.47.0.4     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-d4djv-3449966493                         1/1     Running            0             135m   10.42.0.4     sv-qserv-worker-1    <none>           <none>
```

**Comment by GregBlow** [comment]
ah, having deleted pods and rerun the tests. We have some pods with status ImagePullBackOff, e.g.
```
default                 qserv-ingest-fpq7j-2739416927                         1/2     ImagePullBackOff   0             18m    10.47.0.2     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-fpq7j-3265175513                         1/2     ImagePullBackOff   0             18m    10.44.0.6     sv-qserv-utility-1   <none>           <none>
default                 qserv-ingest-mkt69-1478597742                         0/2     Completed          0             18m    10.42.0.3     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-mkt69-809412122                          1/1     Running            0             18m    10.44.0.7     sv-qserv-utility-1   <none>           <none>
default                 qserv-ingest-mkt69-930127674                          0/2     Completed          0             18m    10.47.0.3     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-64h5j                 1/1     Running            0             18m    10.47.0.7     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-6d2vw                 1/1     Running            0             18m    10.42.0.5     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-cxdtx                 1/1     Running            0             18m    10.42.0.3     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-f67gz                 1/1     Running            0             18m    10.47.0.4     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-k7xl6                 1/1     Running            0             18m    10.42.0.6     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-l5btn                 1/1     Running            0             18m    10.42.0.4     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-pdzwm                 1/1     Running            0             18m    10.47.0.6     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-qv74b                 1/1     Running            0             18m    10.47.0.3     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-r659t                 1/1     Running            0             18m    10.47.0.5     sv-qserv-worker-4    <none>           <none>
default                 qserv-ingest-transactions-cj2ln-vf88d                 1/1     Running            0             18m    10.42.0.7     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-tw2bg-1006216403                         1/2     ImagePullBackOff   0             18m    10.42.0.2     sv-qserv-worker-1    <none>           <none>
default                 qserv-ingest-tw2bg-214417085                          1/2     ImagePullBackOff   0             18m    10.44.0.5     sv-qserv-utility-1   <none>           <none>
```
Describing one of these pods shows the following:
```
ubuntu@sv-qserv-jump:~$ kubectl describe pod qserv-ingest-tw2bg-1006216403
Name:             qserv-ingest-tw2bg-1006216403
Namespace:        default
Priority:         0
Service Account:  argo-workflow
Node:             sv-qserv-worker-1/10.71.0.202
Start Time:       Wed, 12 Apr 2023 13:03:27 +0000
Labels:           app=qserv
                  tier=ingest
                  workflows.argoproj.io/completed=false
                  workflows.argoproj.io/workflow=qserv-ingest-tw2bg
Annotations:      workflows.argoproj.io/node-name: qserv-ingest-tw2bg.register
                  workflows.argoproj.io/template:
                    {"name":"ingest-step","inputs":{"parameters":[{"name":"script","value":"register.sh"}]},"outputs":{},"metadata":{},"container":{"name":"",...
Status:           Pending
IP:               10.42.0.2
IPs:
  IP:           10.42.0.2
Controlled By:  Workflow/qserv-ingest-tw2bg
Containers:
  wait:
    Container ID:  docker://ad4c9e8e362df25dc0ddb2ae6b314b1177677e51eed6cc1e369d1c4e51d6a6c9
    Image:         quay.io/argoproj/argoexec:v3.0.7
    Image ID:      docker-pullable://quay.io/argoproj/argoexec@sha256:3e49c3245977fcab715246f79fa2c94a45dba967a999910e1b07d7702ee81fb1
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
      --loglevel
      info
    State:          Running
      Started:      Wed, 12 Apr 2023 13:03:29 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    qserv-ingest-tw2bg-1006216403 (v1:metadata.name)
      GODEBUG:                          x509ignoreCN=0
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  k8sapi
      ARGO_CONTAINER_NAME:              wait
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /mainctrfs/config from config (rw)
      /mainctrfs/home/qserv/.lsst from repl-creds (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-492hb (ro)
  main:
    Container ID:
    Image:         qserv/ingest:2023.4.1-rc1-dirty
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      register.sh
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      QSERV_INGEST_VERBOSE:  4
      ARGO_CONTAINER_NAME:   main
    Mounts:
      /config from config (rw)
      /home/qserv/.lsst from repl-creds (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-492hb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  repl-creds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  secret-repl-creds-qserv
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-ingest
    Optional:  false
  kube-api-access-492hb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  20m                default-scheduler  Successfully assigned default/qserv-ingest-tw2bg-1006216403 to sv-qserv-worker-1
  Normal   Pulled     20m                kubelet            Container image "quay.io/argoproj/argoexec:v3.0.7" already present on machine
  Normal   Created    20m                kubelet            Created container wait
  Normal   Started    20m                kubelet            Started container wait
  Warning  Failed     18m (x5 over 20m)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    18m (x4 over 20m)  kubelet            Pulling image "qserv/ingest:2023.4.1-rc1-dirty"
  Warning  Failed     18m (x4 over 20m)  kubelet            Failed to pull image "qserv/ingest:2023.4.1-rc1-dirty": rpc error: code = Unknown desc = Error response from daemon: manifest for qserv/ingest:2023.4.1-rc1-dirty not found: manifest unknown: manifest unknown
  Warning  Failed     18m (x4 over 20m)  kubelet            Error: ErrImagePull
  Normal   BackOff    6s (x86 over 20m)  kubelet            Back-off pulling image "qserv/ingest:2023.4.1-rc1-dirty"
```

**Comment by GregBlow** [comment]
regards your earlier comment @fjammes `sudo apt install git-lfs` was sufficient to install git-lfs and effect the changes seen.

the clone `head` output is identical to what you posted, also. 

the `dirty` suffix on the image name might be the problem? Pods that completed have `Image:         qserv/ingest:2023.4.1-rc1` e.g.:

```
ubuntu@sv-qserv-jump:/tmp/qserv-ingest$ kubectl describe pod qserv-ingest-mkt69-1478597742
Name:             qserv-ingest-mkt69-1478597742
Namespace:        default
Priority:         0
Service Account:  argo-workflow
Node:             sv-qserv-worker-1/10.71.0.202
Start Time:       Wed, 12 Apr 2023 13:03:33 +0000
Labels:           app=qserv
                  tier=ingest
                  workflows.argoproj.io/completed=true
                  workflows.argoproj.io/workflow=qserv-ingest-mkt69
Annotations:      workflows.argoproj.io/node-name: qserv-ingest-mkt69.register
                  workflows.argoproj.io/outputs: {"exitCode":"0"}
                  workflows.argoproj.io/template:
                    {"name":"ingest-step","inputs":{"parameters":[{"name":"script","value":"register.sh"}]},"outputs":{},"metadata":{},"container":{"name":"",...
Status:           Succeeded
IP:               10.42.0.3
IPs:
  IP:           10.42.0.3
Controlled By:  Workflow/qserv-ingest-mkt69
Containers:
  wait:
    Container ID:  docker://4acbbe8792707dd6740e732e54dcce3f83002c7942320bf8ee2b2f80866d867a
    Image:         quay.io/argoproj/argoexec:v3.0.7
    Image ID:      docker-pullable://quay.io/argoproj/argoexec@sha256:3e49c3245977fcab715246f79fa2c94a45dba967a999910e1b07d7702ee81fb1
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
      --loglevel
      info
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 12 Apr 2023 13:03:36 +0000
      Finished:     Wed, 12 Apr 2023 13:03:37 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      ARGO_POD_NAME:                    qserv-ingest-mkt69-1478597742 (v1:metadata.name)
      GODEBUG:                          x509ignoreCN=0
      ARGO_CONTAINER_RUNTIME_EXECUTOR:  k8sapi
      ARGO_CONTAINER_NAME:              wait
    Mounts:
      /argo/podmetadata from podmetadata (rw)
      /mainctrfs/config from config (rw)
      /mainctrfs/home/qserv/.lsst from repl-creds (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zk9ll (ro)
  main:
    Container ID:  docker://04aec35cd63eb5dc8490f6360327bf5b35d8c4e7a1c8f64afd2076fb7a0b3d80
    Image:         qserv/ingest:2023.4.1-rc1
    Image ID:      docker-pullable://qserv/ingest@sha256:2fa7510d8b19137e10c425559f9c0eabf7c6148cb65559ea959eb80af00e9a07
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      register.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 12 Apr 2023 13:03:36 +0000
      Finished:     Wed, 12 Apr 2023 13:03:37 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      QSERV_INGEST_VERBOSE:  2
      ARGO_CONTAINER_NAME:   main
    Mounts:
      /config from config (rw)
      /home/qserv/.lsst from repl-creds (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zk9ll (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  podmetadata:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  repl-creds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  secret-repl-creds-qserv
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-ingest
    Optional:  false
  kube-api-access-zk9ll:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  35m   default-scheduler  Successfully assigned default/qserv-ingest-mkt69-1478597742 to sv-qserv-worker-1
  Normal  Pulled     35m   kubelet            Container image "quay.io/argoproj/argoexec:v3.0.7" already present on machine
  Normal  Created    35m   kubelet            Created container wait
  Normal  Started    35m   kubelet            Started container wait
  Normal  Pulled     35m   kubelet            Container image "qserv/ingest:2023.4.1-rc1" already present on machine
  Normal  Created    35m   kubelet            Created container main
  Normal  Started    35m   kubelet            Started container main
```

**Comment by GregBlow** [comment]
```
ubuntu@sv-qserv-jump:/tmp/qserv-ingest$ docker manifest inspect qserv/ingest:2023.4.1-rc1
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 11129,
                "digest": "sha256:cdebf13820edbdd8378bb21a499448c9e72952f64155ce5e292235a50ac8f756"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 54917063,
                        "digest": "sha256:e4d61adff2077d048c6372d73c41b0bd68f525ad41f5530af05098a876683055"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 5153034,
                        "digest": "sha256:4ff1945c672b08a1791df62afaaf8aff14d3047155365f9c3646902937f7ffe6"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 10871885,
                        "digest": "sha256:ff5b10aec998344606441aec43a335ab6326f32aae331aab27da16a6bb4ec2be"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 54575903,
                        "digest": "sha256:12de8c754e45686ace9e25d11bee372b070eed5b5ab20aa3b4fab8c936496d02"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 196524297,
                        "digest": "sha256:ada1762e76024dd216336649249fc2470257acc5af277bae3c71710382df345f"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 6290735,
                        "digest": "sha256:2f2b2e030155d32fbf69b4feeced1877ce0e3f21b5f27b98eb080c3ef01a70df"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 19199312,
                        "digest": "sha256:fa63e4e5310b6c6e8fc69825073a49a506de7e0dd1628b292cd59cf050744ef9"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 238,
                        "digest": "sha256:7c5288a5b77966ccab65aaa8529a1985574b516b5ff97c4c447fceb342c4933e"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 2344249,
                        "digest": "sha256:38121472aa0128f87b31fde5c07080418cc17b4a8ee224767b59e24c592ff7d3"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 7346778,
                        "digest": "sha256:ee2b6e802ed2e02e552bf466b48ac5ed46cc349451799fef25bcbae83918fbf0"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 10531493,
                        "digest": "sha256:b498d3ef5dcd1364ada054b0df02980575eac09d25dbd7a3a2bb1ff213c245a6"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 2435,
                        "digest": "sha256:0dddeba05777963e2c8b4000dd50d14251a4d9feed73b90779a4d9fc5a3ebd8b"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 115296,
                        "digest": "sha256:5a7cb9c25a00ec4b17d2a677f857430aa30880ddcc5f8b5f4372e5b9251c3c1a"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 4403767,
                        "digest": "sha256:984a14b04244a5fecdd3c506a041277c0adf32ce5a417e94c7897af527e0f5ec"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 10501696,
                        "digest": "sha256:07f6cbcf707174404601314ade05b75837578da7c0cb26ed5a63795971e0f661"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 143,
                        "digest": "sha256:8e33fa6b3ca40d5618589bcf6fb4202c4fb4e07f5cac3530ed59f8442d44f5c9"
                },
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 2461200,
                        "digest": "sha256:c138c48515a2a81378baa26632721b841193802d4b1a201f4b3c3bd363f98671"
                }
        ]
}
ubuntu@sv-qserv-jump:/tmp/qserv-ingest$ docker manifest inspect qserv/ingest:2023.4.1-rc1-dirty
no such manifest: docker.io/qserv/ingest:2023.4.1-rc1-dirty
```
